<a href="https://colab.research.google.com/github/hsabaghpour/pytorch-training-playground/blob/main/Operation_on_PyTorch_Deep_Learning_Baiscs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch
import numpy as np

In [8]:
tensor_a = torch.tensor([1,2,3,4,5])
tensor_b = torch.tensor([6,7,8,9,10])

In [10]:
tensor_a + tensor_b

tensor([ 7,  9, 11, 13, 15])

In [12]:
# Addition LongHand

torch.add(tensor_a, tensor_b)

tensor([ 7,  9, 11, 13, 15])

In [13]:
# Subtraction

tensor_a - tensor_b

tensor([-5, -5, -5, -5, -5])

In [14]:
#Sub Func
torch.subtract(tensor_a, tensor_b)

tensor([-5, -5, -5, -5, -5])

In [15]:
#Multipication
tensor_a * tensor_b

tensor([ 6, 14, 24, 36, 50])

In [16]:
#Mul Func
torch.mul(tensor_a, tensor_b)

tensor([ 6, 14, 24, 36, 50])

In [17]:
#Division
tensor_a / tensor_b


tensor([0.1667, 0.2857, 0.3750, 0.4444, 0.5000])

In [19]:
# Dev Func
torch.div(tensor_b, tensor_a)

tensor([6.0000, 3.5000, 2.6667, 2.2500, 2.0000])

In [20]:
# Remainders
tensor_b % tensor_a

tensor([0, 1, 2, 1, 0])

In [21]:
# remainder Func
torch.remainder(tensor_a , tensor_b)

tensor([1, 2, 3, 4, 5])

In [22]:
#Exponent /Power
tensor_a ** tensor_b

tensor([      1,     128,    6561,  262144, 9765625])

In [23]:
torch.pow(tensor_a, tensor_b)

tensor([      1,     128,    6561,  262144, 9765625])

In [24]:
torch.pow(tensor_b, tensor_a)

tensor([     6,     49,    512,   6561, 100000])

In [25]:
torch.exp(tensor_a)

tensor([  2.7183,   7.3891,  20.0855,  54.5981, 148.4132])

In [26]:
#Reassignment
tensor_a =torch.add(tensor_a, tensor_b)
tensor_a

tensor([ 7,  9, 11, 13, 15])

#**.add_**

In [27]:
tensor_a.add_(tensor_b)
tensor_a

tensor([13, 16, 19, 22, 25])

In [28]:
tensor_a

tensor([13, 16, 19, 22, 25])