<a href="https://colab.research.google.com/github/hsabaghpour/pytorch-training-playground/blob/main/PyTorch_Tensor_Operations_Reshape_and_Slice_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch

In [3]:
my_torch = torch.arange(20)
my_torch

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19])

In [4]:
#reshape and vies
my_torch = my_torch.reshape(4,5)
my_torch

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])

In [5]:
#if we are not sure about size of data or data is so big and we want to reshape to either specic size of either rows or columns we use -1 for the dimension we are not so sure
my_torch = my_torch.reshape(-1,10)
my_torch

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [6]:
rand_torch = torch.randn(torch.randint(100000,(1,1)))
rand_torch

tensor([ 2.0415, -0.1487,  1.0479,  ...,  0.3011,  2.0272,  1.2136])

In [7]:
rand_torch.reshape(2,-1)

tensor([[ 2.0415, -0.1487,  1.0479,  ..., -0.3089, -0.3693, -0.4709],
        [-1.0881, -1.5000, -0.3959,  ...,  0.3011,  2.0272,  1.2136]])

In [8]:
rand_torch.reshape(-1,2)

tensor([[ 2.0415, -0.1487],
        [ 1.0479,  0.8766],
        [-0.6623,  0.0914],
        ...,
        [ 0.6693, -0.3626],
        [-0.2725,  0.3011],
        [ 2.0272,  1.2136]])

In [9]:
#view func

my_torch2 = my_torch.view(2,10)
my_torch2

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

#**Reshape vs View on PyTorch**

##**Key Differences:**

###**Memory Sharing:**
**reshape()** tries to share memory when possible, while **view()** strictly requires contiguous memory and throws an error if the shape is incompatible.

###**Flexibility**:
**reshape()** is more flexible in terms of memory sharing, potentially saving memory by sharing data. **view()** is stricter, ensuring contiguous memory but requiring compatible shapes.

Choosing between reshape() and view() depends on your specific needs regarding memory usage and shape compatibility in your PyTorch tensor operations.

https://stackoverflow.com/questions/49643225/whats-the-difference-between-reshape-and-view-in-pytorch

**Note** : any chnage in orginal tensor will get uodated on reshape() and view() as well

In [14]:
my_torch6 = torch.arange(30)
my_torch6

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [15]:
my_torch7 = my_torch6.reshape(-1,6)
my_torch7

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29]])

In [16]:
my_torch6[5] = 5883
my_torch6


tensor([   0,    1,    2,    3,    4, 5883,    6,    7,    8,    9,   10,   11,
          12,   13,   14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
          24,   25,   26,   27,   28,   29])

In [17]:
my_torch7

tensor([[   0,    1,    2,    3,    4, 5883],
        [   6,    7,    8,    9,   10,   11],
        [  12,   13,   14,   15,   16,   17],
        [  18,   19,   20,   21,   22,   23],
        [  24,   25,   26,   27,   28,   29]])

#**SLICING**

In [20]:
my_torch7[1:3,2:4]

tensor([[ 8,  9],
        [14, 15]])

In [21]:
my_torch7[:,1]

tensor([ 1,  7, 13, 19, 25])

In [22]:
my_torch7[:,-1]

tensor([5883,   11,   17,   23,   29])

In [23]:
my_torch7[:]

tensor([[   0,    1,    2,    3,    4, 5883],
        [   6,    7,    8,    9,   10,   11],
        [  12,   13,   14,   15,   16,   17],
        [  18,   19,   20,   21,   22,   23],
        [  24,   25,   26,   27,   28,   29]])

In [24]:
my_torch7[::2]

tensor([[   0,    1,    2,    3,    4, 5883],
        [  12,   13,   14,   15,   16,   17],
        [  24,   25,   26,   27,   28,   29]])

In [25]:
my_torch7[::2,::2]

tensor([[ 0,  2,  4],
        [12, 14, 16],
        [24, 26, 28]])

In [26]:
my_torch7[:2:]

tensor([[   0,    1,    2,    3,    4, 5883],
        [   6,    7,    8,    9,   10,   11]])

In [28]:
my_torch7[3::]

tensor([[18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29]])