<a href="https://colab.research.google.com/github/hsabaghpour/pytorch-training-playground/blob/main/PyTorch_Tensor_Operations_Reshape_and_Slice_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch

In [4]:
my_torch = torch.arange(20)
my_torch

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19])

In [5]:
#reshape and vies
my_torch = my_torch.reshape(4,5)
my_torch

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])

In [6]:
#if we are not sure about size of data or data is so big and we want to reshape to either specic size of either rows or columns we use -1 for the dimension we are not so sure
my_torch = my_torch.reshape(-1,10)
my_torch

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [18]:
rand_torch = torch.randn(torch.randint(100000,(1,1)))
rand_torch

tensor([ 2.5995,  0.6725, -1.0979,  ...,  1.3605,  0.8689, -1.6300])

In [20]:
rand_torch.reshape(2,-1)

tensor([[ 2.5995,  0.6725, -1.0979,  ...,  0.7099, -1.7150,  0.3557],
        [-1.5493, -0.8792,  0.1713,  ...,  1.3605,  0.8689, -1.6300]])

In [21]:
rand_torch.reshape(-1,2)

tensor([[ 2.5995,  0.6725],
        [-1.0979, -1.5062],
        [ 0.1821, -1.0879],
        ...,
        [-0.6811,  1.3772],
        [-0.2696,  1.3605],
        [ 0.8689, -1.6300]])

In [22]:
#view func

my_torch2 = my_torch.view(2,10)
my_torch2

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

#**Reshape vs View on PyTorch**

##**Key Differences:**

###**Memory Sharing:**
**reshape()** tries to share memory when possible, while **view()** strictly requires contiguous memory and throws an error if the shape is incompatible.

###**Flexibility**:
**reshape()** is more flexible in terms of memory sharing, potentially saving memory by sharing data. **view()** is stricter, ensuring contiguous memory but requiring compatible shapes.

Choosing between reshape() and view() depends on your specific needs regarding memory usage and shape compatibility in your PyTorch tensor operations.