<a href="https://colab.research.google.com/github/hsabaghpour/pytorch-training-playground/blob/main/Tensors_with_PyTorch_ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


##**TENSORS**

Alright, let's spice it up with some tech talk:

Imagine **tensors** are the **superheroes** of the math world. You've got:

**Scalars**: The lone wolves. They're just single numbers, like the quiet guy at a party (**0-dimensional**).

**Vectors**: Think of these as your party guests lined up in a row, all in one dimension, having a chat (**1-dimensional**).

**Matrices**: Now it's a dinner party! You've got rows and columns of guests interacting with each other (**2-dimensional**).

**Higher-dimensional Tensors**: This is where things get wild. Picture a massive festival with layers upon layers of interactions (**3D, 4D, and beyond**).

In the realm of **deep learning**, tensors are the cool, flexible friends who can shape-shift into different forms and dimensions, making them the perfect data handlers. Whether it's processing images, text, or any other data, these guys are the real MVPs, powering your favorite AI and machine learning models.

And guess what? They often leverage hardware acceleration like **GPUs** for efficient computation, making them super fast and efficient!

So next time you hear **"tensors**," just think of them as the versatile, multi-talented party planners of the data world, making sure everything runs smoothly and efficiently, often with a little help from their speedy **GPU** buddies!


In [1]:
#!pip install torch


In **PyTorch**, **tensors** (represented as **torch.Tensor**) are the fundamental data structures, much like arrays in NumPy but with added capabilities.

The default dtype for a tensor in PyTorch is **float32**, which is optimized for deep learning tasks.

Unlike NumPy arrays, torch.**Tensor** is more suitable for **deep learning** because it supports:

##GPU acceleration
##Automatic differentiation
##Dynamic computation graphs
These features make torch.Tensor ideal for creating and training complex neural networks efficiently.

In [5]:
import torch
import numpy as np


#**LISTS**

In [2]:
my_list = [1, 2, 3,4,5,6,7,8,9,10]
my_list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [3]:
my_multiDim_list = [[1,2,3],[4,5,6],[7,8,9]]
my_multiDim_list

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

#**NUMPY ARRAYS**

In [6]:
np1 = np.random.randint(10, size=(3,5))
np1

array([[0, 1, 9, 4, 0],
       [8, 6, 6, 4, 6],
       [2, 2, 8, 3, 5]])

In [8]:
np2 = np.random.randint((my_list))
np2

array([0, 1, 2, 3, 4, 3, 3, 5, 4, 0])

In [12]:
np3 = np.random.randn(7,6)
np3

array([[ 0.14976029, -1.19030914,  0.72418548, -1.07794123,  0.48389555,
         2.72903319],
       [-0.6985592 , -0.76605572, -0.41356989,  2.23128133,  0.15013093,
        -0.05628684],
       [ 0.62782601, -1.57304163,  0.42264779,  1.4993707 ,  1.05809858,
         1.09048608],
       [ 0.7394042 , -0.6615203 ,  0.17583951,  0.05774619,  0.44303701,
        -1.0788828 ],
       [ 0.87093979,  0.48478241, -0.93971362,  0.72306599, -0.56399585,
         0.52315161],
       [-0.02119752,  0.91570364,  1.75474384,  0.79472777,  0.39830287,
        -0.04249707],
       [ 2.1409115 ,  0.91361613,  1.0645192 ,  0.60463454, -0.91915698,
         1.13589314]])

In [13]:
np3.dtype

dtype('float64')

#**TENSORS**

In [18]:
tensor_np1 = torch.tensor(np1)
tensor_np1

tensor([[0, 1, 9, 4, 0],
        [8, 6, 6, 4, 6],
        [2, 2, 8, 3, 5]])

In [19]:
tensor_2d = torch.rand(2,3)
tensor_2d

tensor([[0.1553, 0.7873, 0.9950],
        [0.9055, 0.9989, 0.8466]])

In [20]:
tensor_2d.dtype

torch.float32

In [21]:
tensor_2d.shape

torch.Size([2, 3])

In [23]:
tensor_3d = torch.randn(8,5,7)
tensor_3d

tensor([[[ 2.0320,  0.0781,  0.2548,  0.3717, -0.1869,  0.7314,  1.1090],
         [ 0.3400, -0.5091, -0.8763,  0.3545,  2.1160, -0.3708,  0.0237],
         [ 1.0824,  0.8199,  1.1826,  0.9133,  0.3059,  0.6722, -1.4261],
         [-0.2642, -0.4632, -0.0306, -0.5457,  0.2780,  0.6233, -0.3770],
         [ 0.1527,  1.1045,  0.6702,  1.5826, -0.6074, -1.4538, -1.1860]],

        [[-0.0617,  1.3029,  0.3113,  0.2367,  1.2274, -1.2939, -0.2673],
         [ 0.1178,  0.7195, -0.6551,  0.8002, -0.5162,  1.4082,  0.8675],
         [-0.9960, -1.2554,  0.0608,  0.1681, -2.2852,  0.3303,  0.2128],
         [-0.6696,  0.1365,  0.6303, -0.0251, -0.9505,  0.8468, -0.4466],
         [-2.8371,  0.9133,  1.6924, -2.6901, -0.9465, -0.0877, -0.7625]],

        [[ 2.4400, -0.1996, -1.5341,  0.8123,  0.0805,  0.5517,  0.0179],
         [ 0.8111, -1.2071,  0.3993, -0.0104, -1.8267, -0.2939,  0.9097],
         [ 1.3172,  0.0741, -0.8640,  0.7436, -0.8535,  1.6053, -0.4358],
         [ 1.7872,  3.1691, -0.787

In [28]:
tensor_z_4d = torch.zeros(3,2,4,7)
tensor_z_4d

tensor([[[[0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0.]]],


        [[[0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0.]]],


        [[[0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0.]]]])